// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLzr_F8E9qCE1nmo4MgRmhWFcUpFa3zHI',
    appId: '1:79889702885:web:30f026721198e019c5190c',
    messagingSenderId: '79889702885',
    projectId: 'fooddeliveryapp-8912b',
    authDomain: 'fooddeliveryapp-8912b.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-8912b.appspot.com',
    measurementId: 'G-F2XRNDJM7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTPmcYW10bFfNSy4u5CohRmj2w6W_gD_4',
    appId: '1:79889702885:android:4078c275597d4f8ec5190c',
    messagingSenderId: '79889702885',
    projectId: 'fooddeliveryapp-8912b',
    storageBucket: 'fooddeliveryapp-8912b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdoVJbiGnnSCzJzlHvl0OoCNknw2EiYpE',
    appId: '1:79889702885:ios:5c3138eebebe9376c5190c',
    messagingSenderId: '79889702885',
    projectId: 'fooddeliveryapp-8912b',
    storageBucket: 'fooddeliveryapp-8912b.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdoVJbiGnnSCzJzlHvl0OoCNknw2EiYpE',
    appId: '1:79889702885:ios:5c3138eebebe9376c5190c',
    messagingSenderId: '79889702885',
    projectId: 'fooddeliveryapp-8912b',
    storageBucket: 'fooddeliveryapp-8912b.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLzr_F8E9qCE1nmo4MgRmhWFcUpFa3zHI',
    appId: '1:79889702885:web:205e1802498a8a54c5190c',
    messagingSenderId: '79889702885',
    projectId: 'fooddeliveryapp-8912b',
    authDomain: 'fooddeliveryapp-8912b.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-8912b.appspot.com',
    measurementId: 'G-5VNHHR8DVZ',
  );
}
